Add create function for range key
godaddy/dynastar pull request #7
Opened 2020-09-17 21:03 UTC by fritzmonkey

2020-09-17 21:23 UTC, msluther requested changes
Functionally it looks great. A minor quibble in the tests. But requesting changes here to ensure we properly document the change.

2020-09-17 21:23 UTC, msluther commented on index.js
> +    this._createKey = createHashKey || createKey;
Ah, so this is just another name for `createKey`. I assume `createHashKey` is preferred. Are we going to deprecate `createKey` and remove it in the next major version?

2020-09-17 21:23 UTC, msluther commented on test/index.test.js
> +      const myWrapped = new Dynastar({
IMHO, make `myWrapped` be a closure variable (ala model/hash/rangekeys) and then in an `afterEach` drop the tables if `myWrapped` exists.  That way the tests aren't accidentally leaking into each other.

2020-09-17 21:23 UTC, msluther commented on index.js
> +    this._createKey = createHashKey || createKey;
Looks like we never properly documented `createKey` in the `README.md`. Can you add documentation for these two new functions, maybe call out that `createHashKey` will be replacing `createKey`?

2020-09-17 22:02 UTC, msluther commented on test/index.test.js
> +    });
```suggestion
    afterEach(function (done) {
      if (myWrapped) {
        myWrapped.dropTables(done);
      } else {
        done();
      }
    });
```

2020-09-17 22:03 UTC, msluther commented on README.md
> +### key creation
```suggestion
### Key creation
```

2020-09-17 22:54 UTC, msluther approved these changes

2020-09-17 22:58 UTC, msluther commented on test/index.test.js
> +    });
Here. this one should pass the linter
```suggestion
      if (myWrapped) {
        return void myWrapped.dropTables(done);
      }
      done();
    });
```

2020-09-22 01:00 UTC, jcrugzz approved these changes

2020-09-24 18:13 UTC, merged